aws_package:
  osx_url: "https://awscli.amazonaws.com/AWSCLIV2.pkg"


aws_template_dir: "{{ ansible_user_dir }}/.aws"
ssh_template_dir: "{{ ansible_user_dir }}/.ssh"

aws_template_files:
  - { src: aws-config.j2, dest: config }
  - { src: aws-credentials.j2, dest: credentials }

aws_profiles:
  - "2019nov-droidedit_rsa"
  - "github2019nov_rsa" 