---
###   AWS KEYS
###
- name: aws credentials and configs
  template:
    src: "{{item.src}}"
    dest: "{{aws_template_dir}}/{{item.dest}}"
    mode: 0600
    backup: yes
  with_items: "{{aws_template_files}}"


###   SSH CONFIG
###
- name: ssh credentials and configs
  template:
    src: "{{item.src}}"
    dest: "{{ssh_template_dir}}/{{item.dest}}"
    mode: "{{item.mode}}"
  with_items: 
    - { src: "ssh-config.j2", dest: "config", mode: "0600" }


###   SSH KEYS
###
- name: ssh pub files
  file:
    path: "{{ssh_template_dir}}/{{item}}.pub"
    mode: 0600
    state: touch
  with_items: "{{aws_profiles}}"

- name: ssh priv files
  file:
    path: "{{ssh_template_dir}}/{{item}}"
    mode: 0600
    state: touch
  with_items: "{{aws_profiles}}"
