---
- name: awscli package [redhat]
  package: 
    name: awscli
  become: yes
  when: ansible_os_family == "RedHat"

- name: create aws configdir [redhat]
  file:
    path: "{{ aws_template_dir }}"
    state: directory
    mode: 0775

- name: create ssh configdir [redhat]
  file:
    path: "{{ ssh_template_dir }}"
    state: directory
    mode: 0700
